server:
  forward-headers-strategy: FRAMEWORK
  port: ${PORT}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: GAC_Academics

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: https://gac-academic.web.app//callback
