server:
  forward-headers-strategy: FRAMEWORK
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: lamd3pz4i
#    keyStoreType: PKCS12
#    keyAlias: tomcat
#security:
#  require-ssl: true


spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
    mongo:
      database: RateMyProfessor

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: https://gac-academic.web.app/callback
