server:
  forward-headers-strategy: FRAMEWORK
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: lamd3pz4i
#    keyStoreType: PKCS12
#    keyAlias: tomcat
#security:
#  require-ssl: true


spring:
  data:
    mongodb:
      uri: mongodb+srv://lambchop97:L4md3pz4i@cluster0.yvpkd.mongodb.net/RateMyProfessor?retryWrites=true&w=majority
    mongo:
      database: RateMyProfessor

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 367650011816-n2apoktasvh21h2iqa0iojgf7ljh2m73.apps.googleusercontent.com
            client-secret: Q5rPl6pkQU-y0QEElcLugBl5
            redirectUri: https://gusties-academics.online/callback
