server:
  forward-headers-strategy: FRAMEWORK
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: lamd3pz4i
#    keyStoreType: PKCS12
#    keyAlias: tomcat
#security:
#  require-ssl: true


spring:
  data:
    mongodb:
      uri: mongodb+srv://lamnemchua:lamnemchua@cluster1.ehhugcv.mongodb.net/?retryWrites=true&w=majority
      database: GAC_Academics

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 464116066266-o4llc9tracimt8hoe50ijvsic1el6iu0.apps.googleusercontent.com
            client-secret: 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
            redirectUri: http://localhost:4200/callback
