
spring:
  data:
    mongodb:
      uri: mongodb+srv://lambchop97:L4md3pz4i@cluster0.yvpkd.mongodb.net/RateMyProfessor?retryWrites=true&w=majority
    mongo:
      database: RateMyProfessor

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 367650011816-pm498nkon2gt0itejd837etjqajorfbd.apps.googleusercontent.com
            client-secret: s9turRS9iRBM9PnMYPQH0_VZ
            redirectUri: http://localhost:4200/callback
